// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetTagSnapshots(arg1, arg2) {
  return window['go']['main']['App']['GetTagSnapshots'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InspectPreset(arg1) {
  return window['go']['main']['App']['InspectPreset'](arg1);
}

export function PickPresetDirectory() {
  return window['go']['main']['App']['PickPresetDirectory']();
}

export function StartPreset(arg1) {
  return window['go']['main']['App']['StartPreset'](arg1);
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}
