// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLogs():Promise<Array<string>>;

export function GetRuntimeStatus():Promise<main.RuntimeSnapshot>;

export function GetTagSnapshots(arg1:string,arg2:string):Promise<Array<main.TagSnapshot>>;

export function GetVersion():Promise<string>;

export function InspectPreset(arg1:string):Promise<main.PresetSummary>;

export function PickPresetDirectory():Promise<string>;

export function StartPreset(arg1:string):Promise<string>;

export function StopService():Promise<void>;
