// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hda} from '../models';
import {context} from '../models';

export function BrowseTags(arg1:number):Promise<Array<hda.ServerTag>>;

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function IsConnected():Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
