// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseTags(arg1) {
  return window['go']['bindings']['ConnectionBinding']['BrowseTags'](arg1);
}

export function Connect(arg1) {
  return window['go']['bindings']['ConnectionBinding']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['bindings']['ConnectionBinding']['Disconnect']();
}

export function IsConnected() {
  return window['go']['bindings']['ConnectionBinding']['IsConnected']();
}

export function Startup(arg1) {
  return window['go']['bindings']['ConnectionBinding']['Startup'](arg1);
}
