// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hda} from '../models';
import {context} from '../models';

export function CancelQuery():Promise<void>;

export function StartQuery(arg1:hda.QueryConfig):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
