// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery() {
  return window['go']['bindings']['QueryBinding']['CancelQuery']();
}

export function StartQuery(arg1) {
  return window['go']['bindings']['QueryBinding']['StartQuery'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['QueryBinding']['Startup'](arg1);
}
