// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hda} from '../models';

export function LoadConfig():Promise<hda.QueryConfig>;

export function SaveConfig(arg1:hda.QueryConfig):Promise<void>;
