// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['bindings']['SettingsBinding']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['bindings']['SettingsBinding']['SaveSettings'](arg1);
}
