// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hda} from '../models';

export function LoadSettings():Promise<hda.AppSettings>;

export function SaveSettings(arg1:hda.AppSettings):Promise<void>;
