// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function FetchDetail(arg1:string):Promise<Record<string, Record<string, any>>>;

export function GetHistory(arg1:number):Promise<Array<main.HistoryEvent>>;

export function GetState():Promise<main.AppState>;

export function PollNow():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;
