import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, Database, FileText, FolderOpen, Play, Power, Search, Server, Tags } from 'lucide-react'
import { api, type Preset, type RuntimeStatus, type TagRow } from '@/lib/api'

type Page = 'overview' | 'tags' | 'config'
const EMPTY: RuntimeStatus = { phase: 'idle', message: '请选择预置目录', presetRoot: '', endpoint: '', startedAt: '', hdaFilesDone: 0, hdaFilesTotal: 0, hdaSkipped: 0, hdaSamples: 0, hdaElapsedMs: 0, importFile: '', tagCount: 0, goodCount: 0, uncertainCount: 0, badCount: 0, waitingCount: 0, daTagCount: 0, playback: [] }

function phaseLabel(phase: string) {
  return ({ idle: '未启动', validating: '校验中', importing: '预存 HDA', starting: '启动中', running: '运行中', stopping: '停止中', failed: '启动失败' } as Record<string, string>)[phase] ?? phase
}
function fmtNumber(value: number | null) { return value == null ? '—' : Number(value).toLocaleString('zh-CN', { maximumFractionDigits: 5 }) }
function fmtTime(value: string) { return value ? `${new Date(value).toLocaleString('zh-CN', { hour12: false, timeZone: 'UTC' })} UTC` : '—' }
function fmtDuration(ms: number) { return ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} 秒` }
function fmtQuality(value: number) { return `0x${(value >>> 0).toString(16).padStart(8, '0').toUpperCase()}` }
function qualityColor(state: string) { return state === '良好' ? 'bg-emerald-50 text-emerald-700' : state === '不确定' ? 'bg-amber-50 text-amber-700' : state === '等待数据' ? 'bg-slate-100 text-slate-600' : 'bg-rose-50 text-rose-700' }

function Metric({ label, value, tone = 'text-foreground' }: { label: string; value: number; tone?: string }) {
  return <div><div className="text-xs text-mutedForeground">{label}</div><div className={`mt-1 text-2xl font-semibold tracking-tight ${tone}`}>{value.toLocaleString()}</div></div>
}

function StatusBadge({ phase }: { phase: string }) {
  const running = phase === 'running'; const working = ['validating', 'importing', 'starting', 'stopping'].includes(phase)
  return <span className={`inline-flex items-center gap-1.5 rounded-sm px-2 py-1 text-xs font-medium ${running ? 'bg-emerald-50 text-emerald-700' : working ? 'bg-amber-50 text-amber-700' : phase === 'failed' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600'}`}><span className={`h-1.5 w-1.5 rounded-full ${running ? 'bg-emerald-500' : working ? 'animate-pulse bg-amber-500' : phase === 'failed' ? 'bg-rose-500' : 'bg-slate-400'}`} />{phaseLabel(phase)}</span>
}

function Overview({ status, logs }: { status: RuntimeStatus; logs: string[] }) {
  const importing = status.phase === 'importing'
  return <div className="space-y-4">
    <section className="card p-5"><div className="flex items-start justify-between"><div><div className="text-sm font-medium">HDA 预存</div><p className="mt-1 text-sm text-mutedForeground">{status.importFile ? `正在处理 ${status.importFile}` : status.hdaFilesTotal ? '服务启动时自动校验并导入预存历史' : '选择数据集后显示导入状态'}</p></div><Database className="h-5 w-5 text-mutedForeground" /></div><div className="mt-5 grid grid-cols-3 gap-5"><Metric label="完成文件" value={status.hdaFilesDone} /><div><Metric label="总文件" value={status.hdaFilesTotal} />{status.hdaSkipped > 0 && <div className="mt-1 text-xs text-mutedForeground">已跳过 {status.hdaSkipped} 个未变化文件</div>}</div><div><div className="text-xs text-mutedForeground">新入库样本 / 耗时</div><div className="mt-1 text-lg font-semibold">{status.hdaSamples.toLocaleString()} <span className="text-sm font-normal text-mutedForeground">/ {fmtDuration(status.hdaElapsedMs)}</span></div></div></div>{importing && <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full animate-pulse bg-primary" style={{ width: status.hdaFilesTotal ? `${Math.max(6, status.hdaFilesDone / status.hdaFilesTotal * 100)}%` : '10%' }} /></div>}</section>
    <section className="card p-5"><div className="flex items-center justify-between"><div><div className="text-sm font-medium">位号状态</div><p className="mt-1 text-sm text-mutedForeground">{status.daTagCount > 0 ? 'DA 当前质量分布' : '纯 HDA 数据集：最新历史样本质量分布'}</p></div><Tags className="h-5 w-5 text-mutedForeground" /></div><div className="mt-5 grid grid-cols-5 gap-4"><Metric label="总位号" value={status.tagCount} /><Metric label="良好" value={status.goodCount} tone="text-emerald-700" /><Metric label="不确定" value={status.uncertainCount} tone="text-amber-700" /><Metric label="异常" value={status.badCount} tone="text-rose-700" /><Metric label="等待" value={status.waitingCount} tone="text-slate-600" /></div></section>
    <section className="card overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><div className="text-sm font-medium">DA 轮播</div><p className="mt-1 text-sm text-mutedForeground">每份 DA 文件独立维护播放游标，提交与实时 HDA 入库在同一事务完成。</p></div><Activity className="h-5 w-5 text-mutedForeground" /></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#faf9f7] text-xs text-mutedForeground"><tr><th className="px-5 py-3 font-medium">文件</th><th className="px-4 py-3 font-medium">周期</th><th className="px-4 py-3 font-medium">当前行 / 总行</th><th className="px-4 py-3 font-medium">最近提交</th><th className="px-4 py-3 font-medium">状态</th></tr></thead><tbody>{status.playback.length === 0 ? <tr><td className="px-5 py-7 text-mutedForeground" colSpan={5}>尚未启动 DA 轮播。</td></tr> : status.playback.map(file => <tr className="border-t" key={file.name}><td className="px-5 py-3 font-medium">{file.name}{file.lastError && <div className="mt-1 max-w-md truncate text-xs text-rose-600">{file.lastError}</div>}</td><td className="px-4 py-3 text-mutedForeground">{fmtDuration(file.periodMs)}</td><td className="px-4 py-3">{file.currentRow} / {file.totalRows}</td><td className="px-4 py-3 text-mutedForeground">{fmtTime(file.lastCommit)}</td><td className="px-4 py-3"><span className={`rounded-sm px-2 py-1 text-xs ${file.status === '运行中' ? 'bg-emerald-50 text-emerald-700' : file.status === '异常' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{file.status}</span></td></tr>)}</tbody></table></div></section>
    <section className="card overflow-hidden"><div className="border-b px-5 py-4"><div className="text-sm font-medium">运行日志</div><p className="mt-1 text-sm text-mutedForeground">最近 {logs.length} 条记录</p></div><pre className="max-h-56 overflow-auto bg-[#fbfaf8] p-4 font-mono text-xs leading-6 text-mutedForeground">{logs.length ? logs.join('') : '暂无日志。'}</pre></section>
  </div>
}

function TagsPage({ tags, query, filter, onQuery, onFilter }: { tags: TagRow[]; query: string; filter: string; onQuery: (v: string) => void; onFilter: (v: string) => void }) {
  return <div className="card overflow-hidden"><div className="flex items-center gap-3 border-b p-4"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-mutedForeground" /><input value={query} onChange={e => onQuery(e.target.value)} className="input w-full pl-9" placeholder="搜索位号名称" /></div><select className="input w-32" value={filter} onChange={e => onFilter(e.target.value)}><option>全部</option><option>良好</option><option>不确定</option><option>异常</option><option>等待数据</option></select></div><div className="overflow-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="sticky top-0 bg-[#faf9f7] text-xs text-mutedForeground"><tr><th className="px-5 py-3 font-medium">位号</th><th className="px-4 py-3 font-medium">DA 值</th><th className="px-4 py-3 font-medium">DA 质量</th><th className="px-4 py-3 font-medium">DA SourceTime (UTC)</th><th className="px-4 py-3 font-medium">入库 HDA 值</th><th className="px-4 py-3 font-medium">入库 HDA 质量</th><th className="px-4 py-3 font-medium">HDA SourceTime (UTC)</th></tr></thead><tbody>{tags.length ? tags.map(row => <tr className="border-t" key={row.name}><td className="px-5 py-3 font-medium">{row.name}</td><td className="px-4 py-3">{fmtNumber(row.daValue)}</td><td className="px-4 py-3"><span className={`rounded-sm px-2 py-1 text-xs ${qualityColor(row.daState)}`}>{row.daState} · {fmtQuality(row.daQuality)}</span></td><td className="px-4 py-3 text-xs text-mutedForeground">{fmtTime(row.daTime)}</td><td className="px-4 py-3">{fmtNumber(row.hdaValue)}</td><td className="px-4 py-3"><span className={`rounded-sm px-2 py-1 text-xs ${qualityColor(row.hdaState)}`}>{row.hdaState} · {fmtQuality(row.hdaQuality)}</span></td><td className="px-4 py-3 text-xs text-mutedForeground">{fmtTime(row.hdaTime)}</td></tr>) : <tr><td className="px-5 py-10 text-mutedForeground" colSpan={7}>服务启动后可查看位号实时 VQT 与最近入库 HDA VQT。</td></tr>}</tbody></table></div></div>
}

function ConfigPage({ preset }: { preset: Preset | null }) {
  if (!preset) return <div className="card p-8 text-sm text-mutedForeground">选择预置目录后显示只读配置与数据集摘要。</div>
  return <div className="space-y-4"><section className="card p-5"><div className="text-sm font-medium">数据集摘要</div><div className="mt-4 overflow-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-[#faf9f7] text-xs text-mutedForeground"><tr><th className="px-3 py-2">文件</th><th className="px-3 py-2">类型</th><th className="px-3 py-2">行数</th><th className="px-3 py-2">位号</th><th className="px-3 py-2">辅助列</th><th className="px-3 py-2">轮播周期</th></tr></thead><tbody>{preset.files.map(file => <tr className="border-t" key={`${file.kind}/${file.name}`}><td className="px-3 py-3 font-medium">{file.name}</td><td className="px-3 py-3">{file.kind}</td><td className="px-3 py-3">{file.rows.toLocaleString()}</td><td className="px-3 py-3">{file.tagCount}</td><td className="px-3 py-3 text-mutedForeground">status {file.statusColumns} · hda_value {file.hdaValueColumns} · hda_status {file.hdaStatusColumns}</td><td className="px-3 py-3">{file.kind === 'DA' ? fmtDuration(file.periodMs) : '—'}</td></tr>)}</tbody></table></div></section><section className="card overflow-hidden"><div className="border-b px-5 py-4"><div className="text-sm font-medium">config.yaml</div><p className="mt-1 text-sm text-mutedForeground">只读展示 · {preset.configPath}</p></div><pre className="max-h-[420px] overflow-auto bg-[#fbfaf8] p-5 font-mono text-xs leading-6 text-foreground">{preset.configYaml}</pre></section></div>
}

export default function App() {
  const [page, setPage] = useState<Page>('overview'); const [status, setStatus] = useState<RuntimeStatus>(EMPTY); const [preset, setPreset] = useState<Preset | null>(null); const [logs, setLogs] = useState<string[]>([]); const [tags, setTags] = useState<TagRow[]>([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('全部'); const [notice, setNotice] = useState(''); const [version, setVersion] = useState('')
  const busy = !['idle', 'failed'].includes(status.phase); const canStart = !!preset && !preset.error && !busy; const canStop = ['validating', 'importing', 'starting', 'running'].includes(status.phase)
  const refresh = useCallback(async () => { const [nextStatus, nextLogs] = await Promise.all([api.getStatus(), api.getLogs()]); setStatus(nextStatus); setLogs(nextLogs); if (nextStatus.phase === 'running') setTags(await api.getTags(query, filter)); else setTags([]) }, [query, filter])
  useEffect(() => { api.getVersion().then(setVersion); refresh(); const id = window.setInterval(() => { refresh().catch(() => {}) }, 1000); return () => window.clearInterval(id) }, [refresh])
  useEffect(() => { if (notice) { const id = window.setTimeout(() => setNotice(''), 3500); return () => window.clearTimeout(id) } }, [notice])
  const choose = async () => { const root = await api.pickDirectory(); if (!root) return; const result = await api.inspect(root); setPreset(result); if (result.error) setNotice(result.error) }
  const start = async () => { if (!preset) return; const error = await api.start(preset.root); if (error) setNotice(error); else refresh() }
  const title = useMemo(() => page === 'overview' ? '运行概览' : page === 'tags' ? '位号详情' : '配置与数据集', [page])
  return <div className="flex h-screen overflow-hidden"><aside className="flex w-[248px] shrink-0 flex-col border-r bg-card p-4"><div className="flex items-center gap-3 px-2 py-3"><div className="grid h-8 w-8 place-items-center rounded-md bg-primary text-sm font-bold text-white">H</div><div><div className="text-sm font-semibold">HDA Mocker 4</div><div className="text-xs text-mutedForeground">{version || '桌面控制台'}</div></div></div><nav className="mt-6 space-y-1"><button className={`nav-item ${page === 'overview' ? 'nav-item-active' : ''}`} onClick={() => setPage('overview')}><Activity className="h-4 w-4" />运行概览</button><button className={`nav-item ${page === 'tags' ? 'nav-item-active' : ''}`} onClick={() => setPage('tags')}><Tags className="h-4 w-4" />位号详情</button><button className={`nav-item ${page === 'config' ? 'nav-item-active' : ''}`} onClick={() => setPage('config')}><FileText className="h-4 w-4" />配置与数据集</button></nav><div className="mt-auto rounded-md bg-muted p-3 text-xs leading-5 text-mutedForeground">选择预置目录后校验数据集；HDA 预存、DA 轮播与实时入库由同一个服务实例管理。</div></aside><main className="flex min-w-0 flex-1 flex-col"><header className="flex shrink-0 items-center justify-between border-b bg-card px-7 py-4"><div><h1 className="text-lg font-semibold">{title}</h1><div className="mt-1 flex items-center gap-2 text-xs text-mutedForeground"><StatusBadge phase={status.phase} /><span className="max-w-[460px] truncate">{status.message}</span></div></div><div className="flex items-center gap-2"><button className="button-secondary" disabled={busy} onClick={choose}><FolderOpen className="h-4 w-4" />选择目录</button>{canStop ? <button className="button-secondary border-rose-200 text-rose-700" onClick={() => api.stop()}><Power className="h-4 w-4" />停止</button> : <button className="button-primary" disabled={!canStart} onClick={start}><Play className="h-4 w-4" />启动服务</button>}</div></header><div className="border-b bg-[#fbfaf8] px-7 py-2 text-xs text-mutedForeground"><Server className="mr-1 inline h-3.5 w-3.5" />{preset?.root || '尚未选择预置目录'}{status.endpoint && <span className="ml-4">Endpoint: {status.endpoint}</span>}</div><div className="flex-1 overflow-y-auto p-7">{notice && <div className="mb-4 rounded-md border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{notice}</div>}{page === 'overview' ? <Overview status={status} logs={logs} /> : page === 'tags' ? <TagsPage tags={tags} query={query} filter={filter} onQuery={setQuery} onFilter={setFilter} /> : <ConfigPage preset={preset} />}</div></main></div>
}
